package rendering

import (
	"fmt"

	promv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
)

// RenderMarkdown renders Markdown
func RenderMarkdown(ruleGroups []promv1.RuleGroup) string {
	document := "<!-- Generated by promdoc. DO NOT EDIT. -->\n\n"
	document += "# Alerts\n"

	var currentGroup string
	for _, ruleGroup := range ruleGroups {
		if currentGroup != ruleGroup.Name {
			currentGroup = ruleGroup.Name
			document += "\n## " + ruleGroup.Name + "\n\n"
			document += "|Name|Summary|Severity|Runbook|\n"
			document += "|---|---|---|---|\n"
		}

		for _, rule := range ruleGroup.Rules {
			if rule.Alert == "" {
				continue
			}

			summary := rule.Annotations["summary"]
			severity := rule.Labels["severity"]

			runbookURL := rule.Annotations["runbook_url"]
			if runbookURL != "" {
				runbookURL = fmt.Sprintf("[%s](%s)", runbookURL, runbookURL)
			}

			document += fmt.Sprintf("|%s|%s|%s|%s|\n", rule.Alert, summary, severity, runbookURL)
		}
	}

	return document
}
